"""create timesheets table

Revision ID: 0bf3c4001ca5
Revises: 6a370704cee5
Create Date: 2026-08-03 18:16:37.990852

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bf3c4001ca5"
down_revision: str | Sequence[str] | None = "6a370704cee5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timesheets",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_timesheets_employee_id", "timesheets", ["employee_id"], unique=False)
    op.create_index("ix_timesheets_end_date", "timesheets", ["end_date"], unique=False)
    op.create_index("ix_timesheets_start_date", "timesheets", ["start_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_timesheets_start_date", table_name="timesheets")
    op.drop_index("ix_timesheets_end_date", table_name="timesheets")
    op.drop_index("ix_timesheets_employee_id", table_name="timesheets")
    op.drop_table("timesheets")
    # ### end Alembic commands ###
