"""create hr employees table

Revision ID: ebecec46153d
Revises: 6407cfec37d7
Create Date: 2026-08-02 20:50:24.882993

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebecec46153d"
down_revision: str | Sequence[str] | None = "6407cfec37d7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hr_employees",
        sa.Column("employee_number", sa.String(length=50), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("department_id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("manager_id", sa.Uuid(), nullable=True),
        sa.Column("hire_date", sa.Date(), nullable=False),
        sa.Column("employment_status", sa.String(length=50), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["manager_id"], ["hr_employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["position_id"], ["positions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_hr_employees_email"),
        sa.UniqueConstraint("employee_number", name="uq_hr_employees_employee_number"),
    )
    op.create_index(
        "ix_hr_employees_department_id", "hr_employees", ["department_id"], unique=False
    )
    op.create_index(
        "ix_hr_employees_employment_status", "hr_employees", ["employment_status"], unique=False
    )
    op.create_index("ix_hr_employees_full_name", "hr_employees", ["full_name"], unique=False)
    op.create_index("ix_hr_employees_location_id", "hr_employees", ["location_id"], unique=False)
    op.create_index("ix_hr_employees_manager_id", "hr_employees", ["manager_id"], unique=False)
    op.create_index(
        "ix_hr_employees_organization_id", "hr_employees", ["organization_id"], unique=False
    )
    op.create_index("ix_hr_employees_position_id", "hr_employees", ["position_id"], unique=False)
    op.create_index("ix_hr_employees_team_id", "hr_employees", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_hr_employees_team_id", table_name="hr_employees")
    op.drop_index("ix_hr_employees_position_id", table_name="hr_employees")
    op.drop_index("ix_hr_employees_organization_id", table_name="hr_employees")
    op.drop_index("ix_hr_employees_manager_id", table_name="hr_employees")
    op.drop_index("ix_hr_employees_location_id", table_name="hr_employees")
    op.drop_index("ix_hr_employees_full_name", table_name="hr_employees")
    op.drop_index("ix_hr_employees_employment_status", table_name="hr_employees")
    op.drop_index("ix_hr_employees_department_id", table_name="hr_employees")
    op.drop_table("hr_employees")
    # ### end Alembic commands ###
