"""create attendance events table

Revision ID: 1c4f19907e49
Revises: e7a8ed87ea45
Create Date: 2026-08-03 14:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c4f19907e49"
down_revision: str | Sequence[str] | None = "e7a8ed87ea45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance_events",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("shift_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "CLOCK_IN",
                "CLOCK_OUT",
                "BREAK_IN",
                "BREAK_OUT",
                name="attendance_event_type",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "SYSTEM",
                "MANUAL",
                "IMPORT",
                name="attendance_event_source",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("remarks", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["employee_id"], ["hr_employees.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["shift_id"], ["shifts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_attendance_events_employee_id", "attendance_events", ["employee_id"], unique=False
    )
    op.create_index(
        "ix_attendance_events_event_time", "attendance_events", ["event_time"], unique=False
    )
    op.create_index(
        "ix_attendance_events_shift_id", "attendance_events", ["shift_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attendance_events_shift_id", table_name="attendance_events")
    op.drop_index("ix_attendance_events_event_time", table_name="attendance_events")
    op.drop_index("ix_attendance_events_employee_id", table_name="attendance_events")
    op.drop_table("attendance_events")
    # ### end Alembic commands ###
